import { fonts } from '@repo/design-system/lib/fonts';
import type { Metadata } from 'next';
import '@repo/design-system/styles/globals.css';
import './globals.css';
import type { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProperties = {
  readonly children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProperties) {
  return (
    <html lang="en" className={fonts}>
      <body>{children}</body>
    </html>
  );
}
